site_name: Sidewinder
theme:
  name: material
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
repo_url: https://github.com/stribny/sidewinder
repo_name: stribny/sidewinder
extra:
  generator: false
nav:
    - Introduction: 'index.md'
    - How To:
      - Installation: 'howto/installation.md'
      - Configuration: 'howto/configuration.md'
      - Run the project: 'howto/run.md'
      - Administration: 'howto/admin.md'
      - Frontend: 'howto/frontend.md'
      - Testing: 'howto/testing.md'
      - Create a Django app: 'howto/create-app.md'
      - Server provisioning: 'howto/provisioning.md'
      - Deployment: 'howto/deployment.md'
      - Server management: 'howto/server-management.md'
    - Reference: 
      - Commands: 'reference/commands.md'